CREATE OR REPLACE FORCE VIEW "ICTBENEFICIOSPROD"."PERFILES" ("ID_PERFIL", "CODIGO_TIPO_SERVICIO", "FECHA_CREACION", "CORREO_PERFIL", "OBSERVACIONES", "ID_PERSONA_FISICA", "TIPO_IDEN_FISICA", "IDENTIFICACION", "NOMBRE", "APELLIDO_1", "APELLIDO_2", "ID_PERSONA_JURIDICA", "CED_JURIDICA", "NOMBRE_COMERCIAL", "NOMBRE_REPRESENTANTE", "APELLIDO_1_REPRESENTANTE", "APELLIDO_2_REPRESENTANTE", "ID_LOC_INMUEBLE", "DIRECCION", "TELEFONO_INMUEBLE", "CODIGO", "CORREO_INMUEBLE", "URL_INMUEBLE", "FECHA_APROBACION_INMUEBLE", "FECHA_DESAFILIACION_INMUEBLE", "FECHA_RECHAZO_INMUEBLE", "APROBADO_INMUEBLE", "DESAFILIADO_INMUEBLE", "RECHAZADO_INMUEBLE", "MOTIVO_RECHAZO_INMUEBLE", "ID_PROVINCIA", "NOMBRE_PROVINCIA", "COD_PROVINCIA", "ID_CANTON", "NOMBRE_CANTON", "COD_CANTON", "ID_DISTRITO", "NOMBRE_DISTRITO", "COD_DISTRITO", "ID_EMPRESA", "NOM_REPRESENTANTE_EMPRESA", "PRIMER_APE_EMPRESA", "SEGUNDO_APE_EMPRESA", "CORREO_NOTIFICACIONES", "TELEFONO_EMPRESA", "URL_EMPRESA", "RAZON_SOCIAL_EMPRESA", "FECHA_APROBACION_EMPRESA", "FECHA_DESAFILIACION_EMPRESA", "FECHA_RECHAZO_EMPRESA", "APROBADO_EMPRESA", "DESAFILIADO_EMPRESA", "RECHAZADO_EMPRESA", "MOTIVO_RECHAZO_EMPRESA") AS 
  SELECT p.ID_PERFIL , p.CODIGO_TIPO_SERVICIO , p.FECHA_CREACION , p.CORREO AS CORREO_PERFIL, p.OBSERVACIONES,
pf.ID_PERSONA_FISICA , pf.TIPO_IDEN_FISICA , pf.IDENTIFICACION , pf.NOMBRE , pf.APELLIDO_1 , pf.APELLIDO_2 ,
pj.ID_PERSONA_JURIDICA , pj.CED_JURIDICA , pj.NOMBRE_COMERCIAL , pj.NOMBRE_REPRESENTANTE , pj.APELLIDO_1_REPRESENTANTE , pj.APELLIDO_2_REPRESENTANTE ,
l.ID_LOC_INMUEBLE , l.DIRECCION , l.TELEFONO AS TELEFONO_INMUEBLE, COALESCE(l.CODIGO,'0') AS CODIGO, l.CORREO  AS CORREO_INMUEBLE, l.URL_INMUEBLE1 AS URL_INMUEBLE, 
l.FECHA_APROBACION AS FECHA_APROBACION_INMUEBLE , l. FECHA_DESAFILIACION AS FECHA_DESAFILIACION_INMUEBLE , l.FECHA_RECHAZO AS FECHA_RECHAZO_INMUEBLE ,l.APROBADO AS APROBADO_INMUEBLE , 
l.DESAFILIADO AS DESAFILIADO_INMUEBLE, l.RECHAZADO AS RECHAZADO_INMUEBLE, l.MOTIVO_RECHAZO AS MOTIVO_RECHAZO_INMUEBLE ,
pro.ID_PROVINCIA , pro.NOMBRE AS NOMBRE_PROVINCIA, pro.COD_PROVINCIA,
c.ID_CANTON , c.NOMBRE AS NOMBRE_CANTON, c.COD_CANTON,
d.ID_DISTRITO , d.NOMBRE AS NOMBRE_DISTRITO, d.COD_DISTRITO,
e.ID_EMPRESA , e.NOMBRE_REPRESENTANTE AS NOM_REPRESENTANTE_EMPRESA, e.PRIMER_APE AS  PRIMER_APE_EMPRESA, e.SEGUNDO_APE AS SEGUNDO_APE_EMPRESA, e.CORREO AS CORREO_NOTIFICACIONES,
e.TELEFONO AS TELEFONO_EMPRESA, e.URL AS URL_EMPRESA , e.RAZON_SOCIAL AS RAZON_SOCIAL_EMPRESA, e.FECHA_APROBADO AS FECHA_APROBACION_EMPRESA , e.FECHA_DESAFILIADO AS FECHA_DESAFILIACION_EMPRESA , 
e.FECHA_RECHAZO AS FECHA_RECHAZO_EMPRESA , e.APROBADO AS APROBADO_EMPRESA , e.DESAFILIADO AS DESAFILIADO_EMPRESA, e.RECHAZADO AS RECHAZADO_EMPRESA, e.MOTIVO_RECHAZO AS MOTIVO_RECHAZO_EMPRESA
FROM PERFIL p
FULL OUTER JOIN LOCALIZACION l
ON l.ID_PERFIL = p.ID_PERFIL
LEFT OUTER JOIN PERSONA_FISICA pf
ON pf.ID_PERSONA_FISICA = p.PERSONA_FISICA_ID
LEFT OUTER JOIN PERSONA_JURIDICA pj
ON pj.ID_PERSONA_JURIDICA = p.PERSONA_JURIDICA_ID
LEFT OUTER JOIN PROVINCIA pro
ON pro.ID_PROVINCIA = l.PROVINCIA
LEFT OUTER JOIN CANTON c
ON c.ID_CANTON = l.CANTON
LEFT OUTER JOIN DISTRITO d
ON d.ID_DISTRITO = l.DISTRITO
LEFT OUTER JOIN EMPRESA e 
ON e.ID_EMPRESA = p.EMPRESA_ID
ORDER BY p.ID_PERFIL;